// create table
//   public.event_sessions (
//     id bigint generated by default as identity,
//     created_at timestamp with time zone null default now(),
//     event_id bigint not null,
//     session_id bigint not null,
//     constraint event_sessions_pkey primary key (id),
//     constraint event_sessions_event_id_fkey foreign key (event_id) references events (id) on delete cascade,
//     constraint event_sessions_session_id_fkey foreign key (session_id) references sessions (id) on delete cascade
//   ) tablespace pg_default;
