// create table
//   public.scores (
//     id bigint generated by default as identity,
//     strokes smallint not null,
//     hole smallint not null,
//     putts smallint null default '0'::smallint,
//     beers smallint null default '0'::smallint,
//     created_at timestamp with time zone null default now(),
//     extra_strokes smallint not null default '0'::smallint,
//     points smallint not null default '0'::smallint,
//     scorecard_id bigint not null,
//     to_par smallint not null default '0'::smallint,
//     fines smallint not null default '0'::smallint,
//     ciders smallint null default '0'::smallint,
//     constraint scores_pkey primary key (id),
//     constraint scores_scorecard_id_hole_key unique (scorecard_id, hole),
//     constraint scores_scorecard_id_fkey foreign key (scorecard_id) references scorecards (id) on delete cascade
//   ) tablespace pg_default;

// create trigger summarize_scorecard_on_score
// after insert
// or delete
// or
// update on scores for each row
// execute function update_scorecard ();
