// create table
//   public.scorecards (
//     id bigint generated by default as identity,
//     created_at timestamp with time zone null default now(),
//     points smallint null,
//     session_id bigint not null,
//     course_id bigint not null,
//     strokes smallint null,
//     putts smallint null,
//     week_points real null,
//     given_strokes smallint not null,
//     team_index smallint null,
//     through smallint null,
//     to_par smallint null,
//     constraint scorecards_pkey primary key (id),
//     constraint scorecards_course_id_fkey foreign key (course_id) references courses (id),
//     constraint scorecards_session_id_fkey foreign key (session_id) references sessions (id) on delete cascade
//   ) tablespace pg_default;
